// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://worhlsqtqwvusuqjxttk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indvcmhsc3F0cXd2dXN1cWp4dHRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NzA5NTQsImV4cCI6MjA2NDM0Njk1NH0.8ZPuFIpVVf88ATUyEBl1LUv-0SJKaJSjLMN2l9yUGAU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);